# Generated by Django 2.2.7 on 2020-09-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Porson',
            fields=[
                ('porson_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email_id', models.EmailField(default=0, max_length=254)),
                ('image', models.ImageField(upload_to='photo')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('cotegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchengine.Category')),
            ],
        ),
    ]
