# Generated by Django 2.2.7 on 2020-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porson',
            name='rant',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
