# Generated by Django 2.2.7 on 2020-09-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0002_porson_rant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porson',
            old_name='rant',
            new_name='wage',
        ),
    ]
