# Generated by Django 2.2.7 on 2020-09-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0004_auto_20200920_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
