# Generated by Django 2.2.7 on 2020-09-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0005_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='contact',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
